import { type Word, type WordForm } from './types'

export function emptyWordForm(): WordForm {
  return {
    word: '',
    phonetic: '',
    phoneticUs: '',
    phoneticUk: '',
    lemma: '',
    translation: '',
    translationShort: '',
    exampleSentence: '',
    exampleSentences: '',
    audioUrl: '',
    imageUrl: '',
    videoUrl: '',
    difficulty: 1,
    sortOrder: 0,
    partOfSpeech: '',
    definition: '',
    synonyms: '',
    antonyms: '',
    wordFamily: '',
    collocations: '',
    frequency: 1,
    importance: 1,
    tags: '',
    notes: '',
    syllables: '',
    stressPattern: '',
    cefrLevel: '',
    register: '',
    etymology: '',
    morphology: '',
    derivations: '',
    mnemonic: '',
    homophones: '',
    usageNotes: '',
    grammarPatterns: '',
  }
}

function text(value: string | undefined): string {
  return value ?? ''
}

export function wordToForm(word: Word): WordForm {
  return {
    ...emptyWordForm(),
    word: text(word.word),
    phonetic: text(word.phonetic),
    phoneticUs: text(word.phoneticUs),
    phoneticUk: text(word.phoneticUk),
    lemma: text(word.lemma),
    translation: text(word.translation),
    translationShort: text(word.translationShort),
    exampleSentence: text(word.exampleSentence),
    exampleSentences: text(word.exampleSentences),
    audioUrl: text(word.audioUrl),
    imageUrl: text(word.imageUrl),
    videoUrl: text(word.videoUrl),
    difficulty: word.difficulty ?? 1,
    sortOrder: word.sortOrder ?? 0,
    partOfSpeech: text(word.partOfSpeech),
    definition: text(word.definition),
    synonyms: text(word.synonyms),
    antonyms: text(word.antonyms),
    wordFamily: text(word.wordFamily),
    collocations: text(word.collocations),
    frequency: word.frequency ?? 1,
    importance: word.importance ?? 1,
    tags: text(word.tags),
    notes: text(word.notes),
    syllables: text(word.syllables),
    stressPattern: text(word.stressPattern),
    cefrLevel: text(word.cefrLevel),
    register: text(word.register),
    etymology: text(word.etymology),
    morphology: text(word.morphology),
    derivations: text(word.derivations),
    mnemonic: text(word.mnemonic),
    homophones: text(word.homophones),
    usageNotes: text(word.usageNotes),
    grammarPatterns: text(word.grammarPatterns),
  }
}
