export type Word = {
  id: number
  wordBookId?: number
  word: string
  phonetic?: string
  phoneticUs?: string
  phoneticUk?: string
  lemma?: string
  translation?: string
  exampleSentence?: string
  exampleSentences?: string
  audioUrl?: string
  imageUrl?: string
  videoUrl?: string
  difficulty?: number
  sortOrder?: number
  partOfSpeech?: string
  definition?: string
  synonyms?: string
  antonyms?: string
  wordFamily?: string
  collocations?: string
  frequency?: number
  importance?: number
  tags?: string
  notes?: string
  syllables?: string
  stressPattern?: string
  cefrLevel?: string
  register?: string
  etymology?: string
  morphology?: string
  derivations?: string
  mnemonic?: string
  homophones?: string
  usageNotes?: string
  grammarPatterns?: string
}

export type WordForm = {
  word: string
  phonetic: string
  phoneticUs: string
  phoneticUk: string
  lemma: string
  translation: string
  exampleSentence: string
  exampleSentences: string
  audioUrl: string
  imageUrl: string
  videoUrl: string
  difficulty: number
  sortOrder: number
  partOfSpeech: string
  definition: string
  synonyms: string
  antonyms: string
  wordFamily: string
  collocations: string
  frequency: number
  importance: number
  tags: string
  notes: string
  syllables: string
  stressPattern: string
  cefrLevel: string
  register: string
  etymology: string
  morphology: string
  derivations: string
  mnemonic: string
  homophones: string
  usageNotes: string
  grammarPatterns: string
}
