export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/lesson-prep/index',
    'pages/wordbooks/index',
    'pages/anti-forgetting/index',
    'pages/coach/index',
    'pages/login/index',
    'pages/profile/index',
    'pages/profile-edit/index',
    'pages/settings/index',
    'pages/about/index',
    'pages/terms/index',
    'pages/privacy/index',
    'pages/notifications/index',
    'pages/my-students/index',
    'pages/scenario-selection/index',
    'pages/material-selection/index',
    'pages/wordbook-words/index',
    'pages/vocab-test/index',
    'pages/vocab-test-testing/index',
    'pages/vocab-test-result/index',
    'pages/training-records/index',
    'pages/review-word-list/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: '解忧',
    navigationBarTextStyle: 'black',
    backgroundColor: '#f6f5f4',
  },
  tabBar: {
    color: '#787671',
    selectedColor: '#4ECDC4',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/lesson-prep/index',
        text: '备课',
        iconPath: 'assets/tabbar/lesson.png',
        selectedIconPath: 'assets/tabbar/lesson-active.png',
      },
      {
        pagePath: 'pages/wordbooks/index',
        text: '词库',
        iconPath: 'assets/tabbar/wordbooks.png',
        selectedIconPath: 'assets/tabbar/wordbooks-active.png',
      },
      {
        pagePath: 'pages/anti-forgetting/index',
        text: '抗遗忘',
        iconPath: 'assets/tabbar/review.png',
        selectedIconPath: 'assets/tabbar/review-active.png',
      },
      {
        pagePath: 'pages/coach/index',
        text: '陪练中心',
        iconPath: 'assets/tabbar/coach.png',
        selectedIconPath: 'assets/tabbar/coach-active.png',
      },
    ],
  },
})
