/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWordbooksIndexRouteImport } from './routes/_authenticated/wordbooks/index'
import { Route as AuthenticatedVocabRecordsIndexRouteImport } from './routes/_authenticated/vocab-records/index'
import { Route as AuthenticatedVocabQuestionsIndexRouteImport } from './routes/_authenticated/vocab-questions/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUserWordsIndexRouteImport } from './routes/_authenticated/user-words/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStorageIndexRouteImport } from './routes/_authenticated/storage/index'
import { Route as AuthenticatedStorageStatsIndexRouteImport } from './routes/_authenticated/storage-stats/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedNotificationTemplatesIndexRouteImport } from './routes/_authenticated/notification-templates/index'
import { Route as AuthenticatedNotificationChannelsIndexRouteImport } from './routes/_authenticated/notification-channels/index'
import { Route as AuthenticatedMailTemplatesIndexRouteImport } from './routes/_authenticated/mail-templates/index'
import { Route as AuthenticatedMailLogsIndexRouteImport } from './routes/_authenticated/mail-logs/index'
import { Route as AuthenticatedInboxNotificationsIndexRouteImport } from './routes/_authenticated/inbox-notifications/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCoachingIndexRouteImport } from './routes/_authenticated/coaching/index'
import { Route as AuthenticatedCloudUsersIndexRouteImport } from './routes/_authenticated/cloud-users/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedWordbooksBookIdRouteImport } from './routes/_authenticated/wordbooks/$bookId'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedNotificationTemplatesNewRouteImport } from './routes/_authenticated/notification-templates/new'
import { Route as AuthenticatedNotificationTemplatesIdRouteImport } from './routes/_authenticated/notification-templates/$id'
import { Route as AuthenticatedNotificationChannelsNewRouteImport } from './routes/_authenticated/notification-channels/new'
import { Route as AuthenticatedNotificationChannelsIdRouteImport } from './routes/_authenticated/notification-channels/$id'
import { Route as AuthenticatedMailTemplatesNewRouteImport } from './routes/_authenticated/mail-templates/new'
import { Route as AuthenticatedMailTemplatesIdRouteImport } from './routes/_authenticated/mail-templates/$id'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedSettingsOperationLogsIndexRouteImport } from './routes/_authenticated/settings/operation-logs/index'
import { Route as AuthenticatedSettingsLoginHistoryIndexRouteImport } from './routes/_authenticated/settings/login-history/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWordbooksIndexRoute =
  AuthenticatedWordbooksIndexRouteImport.update({
    id: '/wordbooks/',
    path: '/wordbooks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVocabRecordsIndexRoute =
  AuthenticatedVocabRecordsIndexRouteImport.update({
    id: '/vocab-records/',
    path: '/vocab-records/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVocabQuestionsIndexRoute =
  AuthenticatedVocabQuestionsIndexRouteImport.update({
    id: '/vocab-questions/',
    path: '/vocab-questions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserWordsIndexRoute =
  AuthenticatedUserWordsIndexRouteImport.update({
    id: '/user-words/',
    path: '/user-words/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStorageIndexRoute =
  AuthenticatedStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStorageStatsIndexRoute =
  AuthenticatedStorageStatsIndexRouteImport.update({
    id: '/storage-stats/',
    path: '/storage-stats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNotificationTemplatesIndexRoute =
  AuthenticatedNotificationTemplatesIndexRouteImport.update({
    id: '/notification-templates/',
    path: '/notification-templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationChannelsIndexRoute =
  AuthenticatedNotificationChannelsIndexRouteImport.update({
    id: '/notification-channels/',
    path: '/notification-channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailTemplatesIndexRoute =
  AuthenticatedMailTemplatesIndexRouteImport.update({
    id: '/mail-templates/',
    path: '/mail-templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailLogsIndexRoute =
  AuthenticatedMailLogsIndexRouteImport.update({
    id: '/mail-logs/',
    path: '/mail-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxNotificationsIndexRoute =
  AuthenticatedInboxNotificationsIndexRouteImport.update({
    id: '/inbox-notifications/',
    path: '/inbox-notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachingIndexRoute =
  AuthenticatedCoachingIndexRouteImport.update({
    id: '/coaching/',
    path: '/coaching/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCloudUsersIndexRoute =
  AuthenticatedCloudUsersIndexRouteImport.update({
    id: '/cloud-users/',
    path: '/cloud-users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedWordbooksBookIdRoute =
  AuthenticatedWordbooksBookIdRouteImport.update({
    id: '/wordbooks/$bookId',
    path: '/wordbooks/$bookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedNotificationTemplatesNewRoute =
  AuthenticatedNotificationTemplatesNewRouteImport.update({
    id: '/notification-templates/new',
    path: '/notification-templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationTemplatesIdRoute =
  AuthenticatedNotificationTemplatesIdRouteImport.update({
    id: '/notification-templates/$id',
    path: '/notification-templates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationChannelsNewRoute =
  AuthenticatedNotificationChannelsNewRouteImport.update({
    id: '/notification-channels/new',
    path: '/notification-channels/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationChannelsIdRoute =
  AuthenticatedNotificationChannelsIdRouteImport.update({
    id: '/notification-channels/$id',
    path: '/notification-channels/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailTemplatesNewRoute =
  AuthenticatedMailTemplatesNewRouteImport.update({
    id: '/mail-templates/new',
    path: '/mail-templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailTemplatesIdRoute =
  AuthenticatedMailTemplatesIdRouteImport.update({
    id: '/mail-templates/$id',
    path: '/mail-templates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsOperationLogsIndexRoute =
  AuthenticatedSettingsOperationLogsIndexRouteImport.update({
    id: '/operation-logs/',
    path: '/operation-logs/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsLoginHistoryIndexRoute =
  AuthenticatedSettingsLoginHistoryIndexRouteImport.update({
    id: '/login-history/',
    path: '/login-history/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mail-templates/$id': typeof AuthenticatedMailTemplatesIdRoute
  '/mail-templates/new': typeof AuthenticatedMailTemplatesNewRoute
  '/notification-channels/$id': typeof AuthenticatedNotificationChannelsIdRoute
  '/notification-channels/new': typeof AuthenticatedNotificationChannelsNewRoute
  '/notification-templates/$id': typeof AuthenticatedNotificationTemplatesIdRoute
  '/notification-templates/new': typeof AuthenticatedNotificationTemplatesNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/wordbooks/$bookId': typeof AuthenticatedWordbooksBookIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/cloud-users/': typeof AuthenticatedCloudUsersIndexRoute
  '/coaching/': typeof AuthenticatedCoachingIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/inbox-notifications/': typeof AuthenticatedInboxNotificationsIndexRoute
  '/mail-logs/': typeof AuthenticatedMailLogsIndexRoute
  '/mail-templates/': typeof AuthenticatedMailTemplatesIndexRoute
  '/notification-channels/': typeof AuthenticatedNotificationChannelsIndexRoute
  '/notification-templates/': typeof AuthenticatedNotificationTemplatesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/storage-stats/': typeof AuthenticatedStorageStatsIndexRoute
  '/storage/': typeof AuthenticatedStorageIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mail-templates/$id': typeof AuthenticatedMailTemplatesIdRoute
  '/mail-templates/new': typeof AuthenticatedMailTemplatesNewRoute
  '/notification-channels/$id': typeof AuthenticatedNotificationChannelsIdRoute
  '/notification-channels/new': typeof AuthenticatedNotificationChannelsNewRoute
  '/notification-templates/$id': typeof AuthenticatedNotificationTemplatesIdRoute
  '/notification-templates/new': typeof AuthenticatedNotificationTemplatesNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/wordbooks/$bookId': typeof AuthenticatedWordbooksBookIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/cloud-users': typeof AuthenticatedCloudUsersIndexRoute
  '/coaching': typeof AuthenticatedCoachingIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/inbox-notifications': typeof AuthenticatedInboxNotificationsIndexRoute
  '/mail-logs': typeof AuthenticatedMailLogsIndexRoute
  '/mail-templates': typeof AuthenticatedMailTemplatesIndexRoute
  '/notification-channels': typeof AuthenticatedNotificationChannelsIndexRoute
  '/notification-templates': typeof AuthenticatedNotificationTemplatesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/storage-stats': typeof AuthenticatedStorageStatsIndexRoute
  '/storage': typeof AuthenticatedStorageIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/mail-templates/$id': typeof AuthenticatedMailTemplatesIdRoute
  '/_authenticated/mail-templates/new': typeof AuthenticatedMailTemplatesNewRoute
  '/_authenticated/notification-channels/$id': typeof AuthenticatedNotificationChannelsIdRoute
  '/_authenticated/notification-channels/new': typeof AuthenticatedNotificationChannelsNewRoute
  '/_authenticated/notification-templates/$id': typeof AuthenticatedNotificationTemplatesIdRoute
  '/_authenticated/notification-templates/new': typeof AuthenticatedNotificationTemplatesNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/wordbooks/$bookId': typeof AuthenticatedWordbooksBookIdRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/cloud-users/': typeof AuthenticatedCloudUsersIndexRoute
  '/_authenticated/coaching/': typeof AuthenticatedCoachingIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/inbox-notifications/': typeof AuthenticatedInboxNotificationsIndexRoute
  '/_authenticated/mail-logs/': typeof AuthenticatedMailLogsIndexRoute
  '/_authenticated/mail-templates/': typeof AuthenticatedMailTemplatesIndexRoute
  '/_authenticated/notification-channels/': typeof AuthenticatedNotificationChannelsIndexRoute
  '/_authenticated/notification-templates/': typeof AuthenticatedNotificationTemplatesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/storage-stats/': typeof AuthenticatedStorageStatsIndexRoute
  '/_authenticated/storage/': typeof AuthenticatedStorageIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/privacy'
    | '/terms'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/mail-templates/$id'
    | '/mail-templates/new'
    | '/notification-channels/$id'
    | '/notification-channels/new'
    | '/notification-templates/$id'
    | '/notification-templates/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/wordbooks/$bookId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/chats/'
    | '/cloud-users/'
    | '/coaching/'
    | '/help-center/'
    | '/inbox-notifications/'
    | '/mail-logs/'
    | '/mail-templates/'
    | '/notification-channels/'
    | '/notification-templates/'
    | '/settings/'
    | '/storage-stats/'
    | '/storage/'
    | '/tasks/'
    | '/user-words/'
    | '/users/'
    | '/vocab-questions/'
    | '/vocab-records/'
    | '/wordbooks/'
    | '/settings/login-history/'
    | '/settings/operation-logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/privacy'
    | '/terms'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/mail-templates/$id'
    | '/mail-templates/new'
    | '/notification-channels/$id'
    | '/notification-channels/new'
    | '/notification-templates/$id'
    | '/notification-templates/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/wordbooks/$bookId'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/cloud-users'
    | '/coaching'
    | '/help-center'
    | '/inbox-notifications'
    | '/mail-logs'
    | '/mail-templates'
    | '/notification-channels'
    | '/notification-templates'
    | '/settings'
    | '/storage-stats'
    | '/storage'
    | '/tasks'
    | '/user-words'
    | '/users'
    | '/vocab-questions'
    | '/vocab-records'
    | '/wordbooks'
    | '/settings/login-history'
    | '/settings/operation-logs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/privacy'
    | '/terms'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/mail-templates/$id'
    | '/_authenticated/mail-templates/new'
    | '/_authenticated/notification-channels/$id'
    | '/_authenticated/notification-channels/new'
    | '/_authenticated/notification-templates/$id'
    | '/_authenticated/notification-templates/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/wordbooks/$bookId'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/cloud-users/'
    | '/_authenticated/coaching/'
    | '/_authenticated/help-center/'
    | '/_authenticated/inbox-notifications/'
    | '/_authenticated/mail-logs/'
    | '/_authenticated/mail-templates/'
    | '/_authenticated/notification-channels/'
    | '/_authenticated/notification-templates/'
    | '/_authenticated/settings/'
    | '/_authenticated/storage-stats/'
    | '/_authenticated/storage/'
    | '/_authenticated/tasks/'
    | '/_authenticated/user-words/'
    | '/_authenticated/users/'
    | '/_authenticated/vocab-questions/'
    | '/_authenticated/vocab-records/'
    | '/_authenticated/wordbooks/'
    | '/_authenticated/settings/login-history/'
    | '/_authenticated/settings/operation-logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wordbooks/': {
      id: '/_authenticated/wordbooks/'
      path: '/wordbooks'
      fullPath: '/wordbooks/'
      preLoaderRoute: typeof AuthenticatedWordbooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab-records/': {
      id: '/_authenticated/vocab-records/'
      path: '/vocab-records'
      fullPath: '/vocab-records/'
      preLoaderRoute: typeof AuthenticatedVocabRecordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vocab-questions/': {
      id: '/_authenticated/vocab-questions/'
      path: '/vocab-questions'
      fullPath: '/vocab-questions/'
      preLoaderRoute: typeof AuthenticatedVocabQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-words/': {
      id: '/_authenticated/user-words/'
      path: '/user-words'
      fullPath: '/user-words/'
      preLoaderRoute: typeof AuthenticatedUserWordsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage/': {
      id: '/_authenticated/storage/'
      path: '/storage'
      fullPath: '/storage/'
      preLoaderRoute: typeof AuthenticatedStorageIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/storage-stats/': {
      id: '/_authenticated/storage-stats/'
      path: '/storage-stats'
      fullPath: '/storage-stats/'
      preLoaderRoute: typeof AuthenticatedStorageStatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/notification-templates/': {
      id: '/_authenticated/notification-templates/'
      path: '/notification-templates'
      fullPath: '/notification-templates/'
      preLoaderRoute: typeof AuthenticatedNotificationTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-channels/': {
      id: '/_authenticated/notification-channels/'
      path: '/notification-channels'
      fullPath: '/notification-channels/'
      preLoaderRoute: typeof AuthenticatedNotificationChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail-templates/': {
      id: '/_authenticated/mail-templates/'
      path: '/mail-templates'
      fullPath: '/mail-templates/'
      preLoaderRoute: typeof AuthenticatedMailTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail-logs/': {
      id: '/_authenticated/mail-logs/'
      path: '/mail-logs'
      fullPath: '/mail-logs/'
      preLoaderRoute: typeof AuthenticatedMailLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox-notifications/': {
      id: '/_authenticated/inbox-notifications/'
      path: '/inbox-notifications'
      fullPath: '/inbox-notifications/'
      preLoaderRoute: typeof AuthenticatedInboxNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaching/': {
      id: '/_authenticated/coaching/'
      path: '/coaching'
      fullPath: '/coaching/'
      preLoaderRoute: typeof AuthenticatedCoachingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cloud-users/': {
      id: '/_authenticated/cloud-users/'
      path: '/cloud-users'
      fullPath: '/cloud-users/'
      preLoaderRoute: typeof AuthenticatedCloudUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/wordbooks/$bookId': {
      id: '/_authenticated/wordbooks/$bookId'
      path: '/wordbooks/$bookId'
      fullPath: '/wordbooks/$bookId'
      preLoaderRoute: typeof AuthenticatedWordbooksBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/notification-templates/new': {
      id: '/_authenticated/notification-templates/new'
      path: '/notification-templates/new'
      fullPath: '/notification-templates/new'
      preLoaderRoute: typeof AuthenticatedNotificationTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-templates/$id': {
      id: '/_authenticated/notification-templates/$id'
      path: '/notification-templates/$id'
      fullPath: '/notification-templates/$id'
      preLoaderRoute: typeof AuthenticatedNotificationTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-channels/new': {
      id: '/_authenticated/notification-channels/new'
      path: '/notification-channels/new'
      fullPath: '/notification-channels/new'
      preLoaderRoute: typeof AuthenticatedNotificationChannelsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notification-channels/$id': {
      id: '/_authenticated/notification-channels/$id'
      path: '/notification-channels/$id'
      fullPath: '/notification-channels/$id'
      preLoaderRoute: typeof AuthenticatedNotificationChannelsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail-templates/new': {
      id: '/_authenticated/mail-templates/new'
      path: '/mail-templates/new'
      fullPath: '/mail-templates/new'
      preLoaderRoute: typeof AuthenticatedMailTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail-templates/$id': {
      id: '/_authenticated/mail-templates/$id'
      path: '/mail-templates/$id'
      fullPath: '/mail-templates/$id'
      preLoaderRoute: typeof AuthenticatedMailTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/operation-logs/': {
      id: '/_authenticated/settings/operation-logs/'
      path: '/operation-logs'
      fullPath: '/settings/operation-logs/'
      preLoaderRoute: typeof AuthenticatedSettingsOperationLogsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/login-history/': {
      id: '/_authenticated/settings/login-history/'
      path: '/login-history'
      fullPath: '/settings/login-history/'
      preLoaderRoute: typeof AuthenticatedSettingsLoginHistoryIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsLoginHistoryIndexRoute: typeof AuthenticatedSettingsLoginHistoryIndexRoute
  AuthenticatedSettingsOperationLogsIndexRoute: typeof AuthenticatedSettingsOperationLogsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsLoginHistoryIndexRoute:
      AuthenticatedSettingsLoginHistoryIndexRoute,
    AuthenticatedSettingsOperationLogsIndexRoute:
      AuthenticatedSettingsOperationLogsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMailTemplatesIdRoute: typeof AuthenticatedMailTemplatesIdRoute
  AuthenticatedMailTemplatesNewRoute: typeof AuthenticatedMailTemplatesNewRoute
  AuthenticatedNotificationChannelsIdRoute: typeof AuthenticatedNotificationChannelsIdRoute
  AuthenticatedNotificationChannelsNewRoute: typeof AuthenticatedNotificationChannelsNewRoute
  AuthenticatedNotificationTemplatesIdRoute: typeof AuthenticatedNotificationTemplatesIdRoute
  AuthenticatedNotificationTemplatesNewRoute: typeof AuthenticatedNotificationTemplatesNewRoute
  AuthenticatedWordbooksBookIdRoute: typeof AuthenticatedWordbooksBookIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCloudUsersIndexRoute: typeof AuthenticatedCloudUsersIndexRoute
  AuthenticatedCoachingIndexRoute: typeof AuthenticatedCoachingIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedInboxNotificationsIndexRoute: typeof AuthenticatedInboxNotificationsIndexRoute
  AuthenticatedMailLogsIndexRoute: typeof AuthenticatedMailLogsIndexRoute
  AuthenticatedMailTemplatesIndexRoute: typeof AuthenticatedMailTemplatesIndexRoute
  AuthenticatedNotificationChannelsIndexRoute: typeof AuthenticatedNotificationChannelsIndexRoute
  AuthenticatedNotificationTemplatesIndexRoute: typeof AuthenticatedNotificationTemplatesIndexRoute
  AuthenticatedStorageStatsIndexRoute: typeof AuthenticatedStorageStatsIndexRoute
  AuthenticatedStorageIndexRoute: typeof AuthenticatedStorageIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUserWordsIndexRoute: typeof AuthenticatedUserWordsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVocabQuestionsIndexRoute: typeof AuthenticatedVocabQuestionsIndexRoute
  AuthenticatedVocabRecordsIndexRoute: typeof AuthenticatedVocabRecordsIndexRoute
  AuthenticatedWordbooksIndexRoute: typeof AuthenticatedWordbooksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMailTemplatesIdRoute: AuthenticatedMailTemplatesIdRoute,
  AuthenticatedMailTemplatesNewRoute: AuthenticatedMailTemplatesNewRoute,
  AuthenticatedNotificationChannelsIdRoute:
    AuthenticatedNotificationChannelsIdRoute,
  AuthenticatedNotificationChannelsNewRoute:
    AuthenticatedNotificationChannelsNewRoute,
  AuthenticatedNotificationTemplatesIdRoute:
    AuthenticatedNotificationTemplatesIdRoute,
  AuthenticatedNotificationTemplatesNewRoute:
    AuthenticatedNotificationTemplatesNewRoute,
  AuthenticatedWordbooksBookIdRoute: AuthenticatedWordbooksBookIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCloudUsersIndexRoute: AuthenticatedCloudUsersIndexRoute,
  AuthenticatedCoachingIndexRoute: AuthenticatedCoachingIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedInboxNotificationsIndexRoute:
    AuthenticatedInboxNotificationsIndexRoute,
  AuthenticatedMailLogsIndexRoute: AuthenticatedMailLogsIndexRoute,
  AuthenticatedMailTemplatesIndexRoute: AuthenticatedMailTemplatesIndexRoute,
  AuthenticatedNotificationChannelsIndexRoute:
    AuthenticatedNotificationChannelsIndexRoute,
  AuthenticatedNotificationTemplatesIndexRoute:
    AuthenticatedNotificationTemplatesIndexRoute,
  AuthenticatedStorageStatsIndexRoute: AuthenticatedStorageStatsIndexRoute,
  AuthenticatedStorageIndexRoute: AuthenticatedStorageIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUserWordsIndexRoute: AuthenticatedUserWordsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVocabQuestionsIndexRoute: AuthenticatedVocabQuestionsIndexRoute,
  AuthenticatedVocabRecordsIndexRoute: AuthenticatedVocabRecordsIndexRoute,
  AuthenticatedWordbooksIndexRoute: AuthenticatedWordbooksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
